// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.17.3
// source: github.com/ameliaikeda/protoc-gen-router/proto/router.proto

package routerproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Protocol int32

const (
	Protocol_HTTP  Protocol = 0
	Protocol_HTTPS Protocol = 1
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "HTTP",
		1: "HTTPS",
	}
	Protocol_value = map[string]int32{
		"HTTP":  0,
		"HTTPS": 1,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_rawDescGZIP(), []int{0}
}

type RPCHandler struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
}

func (x *RPCHandler) Reset() {
	*x = RPCHandler{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCHandler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCHandler) ProtoMessage() {}

func (x *RPCHandler) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCHandler.ProtoReflect.Descriptor instead.
func (*RPCHandler) Descriptor() ([]byte, []int) {
	return file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_rawDescGZIP(), []int{0}
}

func (x *RPCHandler) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RPCHandler) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type ServiceRouter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ServiceType string   `protobuf:"bytes,2,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	Protocol    Protocol `protobuf:"varint,3,opt,name=protocol,proto3,enum=routerproto.Protocol" json:"protocol,omitempty"`
}

func (x *ServiceRouter) Reset() {
	*x = ServiceRouter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceRouter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRouter) ProtoMessage() {}

func (x *ServiceRouter) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRouter.ProtoReflect.Descriptor instead.
func (*ServiceRouter) Descriptor() ([]byte, []int) {
	return file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceRouter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceRouter) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *ServiceRouter) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_HTTP
}

var file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*RPCHandler)(nil),
		Field:         50000,
		Name:          "routerproto.handler",
		Tag:           "bytes,50000,opt,name=handler",
		Filename:      "github.com/ameliaikeda/protoc-gen-router/proto/router.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceRouter)(nil),
		Field:         60000,
		Name:          "routerproto.router",
		Tag:           "bytes,60000,opt,name=router",
		Filename:      "github.com/ameliaikeda/protoc-gen-router/proto/router.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional routerproto.RPCHandler handler = 50000;
	E_Handler = &file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional routerproto.ServiceRouter router = 60000;
	E_Router = &file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_extTypes[1]
)

var File_github_com_ameliaikeda_protoc_gen_router_proto_router_proto protoreflect.FileDescriptor

var file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_rawDesc = []byte{
	0x0a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6d, 0x65,
	0x6c, 0x69, 0x61, 0x69, 0x6b, 0x65, 0x64, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d,
	0x67, 0x65, 0x6e, 0x2d, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x0a,
	0x52, 0x50, 0x43, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x16,
	0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x22, 0x79, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x31,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x15, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2a, 0x1f, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x08, 0x0a,
	0x04, 0x48, 0x54, 0x54, 0x50, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x54, 0x54, 0x50, 0x53,
	0x10, 0x01, 0x3a, 0x53, 0x0a, 0x07, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x1e, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd0, 0x86,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x50, 0x43, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x52, 0x07,
	0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x3a, 0x55, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x72, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0xe0, 0xd4, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x42, 0x3c,
	0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6d, 0x65,
	0x6c, 0x69, 0x61, 0x69, 0x6b, 0x65, 0x64, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d,
	0x67, 0x65, 0x6e, 0x2d, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x3b, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_rawDescOnce sync.Once
	file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_rawDescData = file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_rawDesc
)

func file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_rawDescGZIP() []byte {
	file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_rawDescOnce.Do(func() {
		file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_rawDescData)
	})
	return file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_rawDescData
}

var file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_goTypes = []interface{}{
	(Protocol)(0),                       // 0: routerproto.Protocol
	(*RPCHandler)(nil),                  // 1: routerproto.RPCHandler
	(*ServiceRouter)(nil),               // 2: routerproto.ServiceRouter
	(*descriptorpb.MethodOptions)(nil),  // 3: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil), // 4: google.protobuf.ServiceOptions
}
var file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_depIdxs = []int32{
	0, // 0: routerproto.ServiceRouter.protocol:type_name -> routerproto.Protocol
	3, // 1: routerproto.handler:extendee -> google.protobuf.MethodOptions
	4, // 2: routerproto.router:extendee -> google.protobuf.ServiceOptions
	1, // 3: routerproto.handler:type_name -> routerproto.RPCHandler
	2, // 4: routerproto.router:type_name -> routerproto.ServiceRouter
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	3, // [3:5] is the sub-list for extension type_name
	1, // [1:3] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_init() }
func file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_init() {
	if File_github_com_ameliaikeda_protoc_gen_router_proto_router_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCHandler); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceRouter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_goTypes,
		DependencyIndexes: file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_depIdxs,
		EnumInfos:         file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_enumTypes,
		MessageInfos:      file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_msgTypes,
		ExtensionInfos:    file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_extTypes,
	}.Build()
	File_github_com_ameliaikeda_protoc_gen_router_proto_router_proto = out.File
	file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_rawDesc = nil
	file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_goTypes = nil
	file_github_com_ameliaikeda_protoc_gen_router_proto_router_proto_depIdxs = nil
}
